//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SES_F1
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionRecord
    {
        public int RecordID { get; set; }
        public string RollNumber { get; set; }
        public string PreviousSchool { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public bool Status { get; set; }
    }
}
