//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SES_F1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string RollNumber { get; set; }
        public System.DateTime Date { get; set; }
        public bool Status { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
