//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SES_F1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public string Designsation { get; set; }
        public int Salary { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
    }
}
